name: CI Pipeline with Firefox

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install && npm install selenium-webdriver mocha

      - name: Setup Firefox and Geckodriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          GECKODRIVER_VERSION=$(curl https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep tag_name | cut -d '"' -f 4)
          wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          tar -xzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          sudo mv geckodriver /usr/bin/geckodriver
          sudo chmod +x /usr/bin/geckodriver
          echo "Geckodriver version: $(geckodriver --version)"
          echo "Firefox version: $(firefox --version)"

      - name: Start server
        run: |
          node server.js &
          sleep 5 # gibt dem Server Zeit zum Starten

      - name: Run tests with Firefox
        run: npx mocha test/test.spec.js
