name: CI Pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                    node-version: 16

            - name: Install dependencies
              run: |
                    npm install
                    npm install selenium-webdriver mocha
            
            - name: Install Google Chrome
              run: |
                    sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
                    sudo dpkg -i google-chrome-stable_current_amd64.deb
                    sudo apt-get install -f

            - name: Start server
              run: |
                    node server.js &
                    sleep 5

            - name: Run tests
              run: |
                    npx mocha test/test.spec.js
